services:
# Database Service:
  dev-sprint-postgres:
    image: postgres:16-alpine
    container_name: dev-sprint-postgres
    environment:
      POSTGRES_USER: dhongorsho
      POSTGRES_PASSWORD: dhongorsho123
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
      - ./Database:/docker-entrypoint-initdb.d
    networks:
      - sprint-network 

# Caching Service:
  dev-sprint-redis:
    image: redis:7-alpine
    container_name: dev-sprint-redis
    ports:
      - "6380:6379"
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - sprint-network 

# RabbitMQ Service:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq_service
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "IUT_Dhongorsho"
      RABBITMQ_DEFAULT_PASS: "Dhongorsho123"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    networks:
      - sprint-network 

# Gateway Service (The Trigger):
  gateway:
    build: ./Gateway
    container_name: dev-sprint-gateway
    depends_on:
      - dev-sprint-postgres
      - dev-sprint-redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # ALLOWS TRIGGERING K6
    environment:
      REDIS_URL: "redis://dev-sprint-redis:6379"
      PORT: 4001
      JWT_SECRET: "dhongorsho"
      IDENTITY_SERVICE_URL: "http://dev-sprint-identity:4002"
      INVENTORY_SERVICE_URL: "http://dev-sprint-inventory:4003"
      KITCHEN_SERVICE_URL: "http://dev-sprint-kitchen:4004"
      NOTIFICATION_SERVICE_URL: "http://dev-sprint-notification:4005" 
    ports:
      - "5001:4001"
    restart: always
    networks:
      - sprint-network 

# Identity Service:
  identity:
    build: ./Identity
    container_name: dev-sprint-identity
    depends_on:
      - dev-sprint-postgres
      - dev-sprint-redis
    environment:
      DATABASE_URL: "postgresql://dhongorsho:dhongorsho123@dev-sprint-postgres:5432/user_db?schema=public"
      REDIS_URL: "redis://dev-sprint-redis:6379"
      PORT: 4002
      JWT_SECRET: "dhongorsho"
    ports:
      - "5002:4002"
    restart: always
    networks:
      - sprint-network 

# Inventory Service:
  inventory:
    build: ./Inventory
    container_name: dev-sprint-inventory
    depends_on:
      - dev-sprint-postgres
      - dev-sprint-redis
      - rabbitmq
    environment:
      DATABASE_URL: "postgresql://dhongorsho:dhongorsho123@dev-sprint-postgres:5432/inventory_db?schema=public"
      REDIS_URL: "redis://dev-sprint-redis:6379"
      PORT: 4003
      RABBITMQ_URL: "amqp://IUT_Dhongorsho:Dhongorsho123@rabbitmq:5672"  
      RABBITMQ_EXCHANGE: "order_exchange" 
    ports:
      - "5003:4003"
    restart: always
    networks:
      - sprint-network 

# Kitchen Service:
  kitchen:
    build: ./Kitchen
    container_name: dev-sprint-kitchen
    depends_on:
      - dev-sprint-postgres
      - dev-sprint-redis
      - rabbitmq
    environment:
      DATABASE_URL: "postgresql://dhongorsho:dhongorsho123@dev-sprint-postgres:5432/kitchen_db?schema=public"
      REDIS_URL: "redis://dev-sprint-redis:6379"
      PORT: 4004
      RABBITMQ_URL: "amqp://IUT_Dhongorsho:Dhongorsho123@rabbitmq:5672"  
      RABBITMQ_EXCHANGE: "order_exchange" 
    ports:
      - "5004:4004"
    restart: always
    networks:
      - sprint-network 

# Notification Service:
  notification:
    build: ./Notification
    container_name: dev-sprint-notification
    depends_on:
      - dev-sprint-postgres
      - dev-sprint-redis
      - rabbitmq
    environment:
      REDIS_URL: "redis://dev-sprint-redis:6379"
      PORT: 4005
      RABBITMQ_URL: "amqp://IUT_Dhongorsho:Dhongorsho123@rabbitmq:5672" 
      RABBITMQ_EXCHANGE: "order_exchange"  
    ports:
      - "5005:4005"
    restart: always
    networks:
      - sprint-network 

# Monitoring:
  prometheus:
    image: prom/prometheus:latest
    container_name: dev-sprint-prometheus
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    restart: always
    networks:
      - sprint-network

  grafana:
    image: grafana/grafana:latest
    container_name: dev-sprint-grafana
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: dhongorsho123
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./Grafana/provisioning:/etc/grafana/provisioning
    restart: always
    networks:
      - sprint-network

# Load Testing Service:
  dev-sprint-k6:
    image: grafana/k6:latest
    container_name: dev-sprint-k6
    volumes:
      - ./Tests/All/load-test.js:/scripts/load-test.js
    networks:
      - sprint-network

volumes:
  user-db-data:
  redis-data:
  rabbitmq_data:
  prometheus-data:
  grafana-data:

networks:
  sprint-network:
    driver: bridge